import re
import json
import numpy as np

from modules.llm import call_llm
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity


embedding_model = SentenceTransformer("all-MiniLM-L6-v2")


# A generated REQ with max similarity below this to ALL extracted requirements
# is considered "not from user input" — candidate for AI-suggested
ORIGIN_THRESHOLD = 0.60

# A generated REQ with max similarity above this is clearly from user input
# (not AI-suggested, just paraphrased)
PARAPHRASE_THRESHOLD = 0.60


def detect_ai_suggested_requirements(extracted_requirements, srs_requirements):
    """
    Compares each SRS requirement against extracted user requirements.
    
    A requirement is flagged as AI-suggested if:
    - Its max cosine similarity to ALL extracted requirements is below ORIGIN_THRESHOLD
    - It is NOT already flagged as a hallucination (handled separately)
    
    Returns:
        candidate_reqs (list of str): REQs that appear to be AI-added
    """

    if not extracted_requirements or not srs_requirements:
        return []

    extracted_texts = [
        r["text"] if isinstance(r, dict) else r
        for r in extracted_requirements
    ]

    extracted_embeddings = embedding_model.encode(extracted_texts).astype("float32")
    srs_embeddings = embedding_model.encode(srs_requirements).astype("float32")

    similarity_matrix = cosine_similarity(srs_embeddings, extracted_embeddings)

    candidates = []

    for i, srs_req in enumerate(srs_requirements):
        max_similarity = float(np.max(similarity_matrix[i]))
        if max_similarity < PARAPHRASE_THRESHOLD:
            candidates.append({
                "req": srs_req,
                "max_similarity": round(max_similarity, 3)
            })

    return candidates


def score_relevance_with_llm(candidates, user_input):
    """
    Uses LLM to judge whether each candidate AI-suggested requirement
    is genuinely helpful and relevant to the user's domain.

    Returns:
        relevant (list of str): requirement texts confirmed as relevant by LLM
        irrelevant (list of str): requirement texts judged as irrelevant/noise
    """

    if not candidates:
        return [], []

    # Format candidates for LLM
    candidate_list = "\n".join(
        [f"{i+1}. {c['req']}" for i, c in enumerate(candidates)]
    )

    prompt = f"""
You are a requirements engineering expert.

The following requirements were generated by an AI system but were NOT explicitly stated 
in the original user requirements. Your job is to judge whether each one is:
- RELEVANT: genuinely helpful, logically implied, or a standard best practice 
  for this type of system
- IRRELEVANT: unrelated, from a different domain, or not useful

User's Original Requirements:
{user_input}

AI-Generated Candidate Requirements (not from user input):
{candidate_list}

Return ONLY valid JSON (no markdown, no explanation):

{{
  "judgments": [
    {{"id": 1, "verdict": "RELEVANT", "reason": "short reason"}},
    {{"id": 2, "verdict": "IRRELEVANT", "reason": "short reason"}}
  ]
}}
"""

    response = call_llm(prompt, temperature=0.1)

    # Strip markdown fences if present
    cleaned = re.sub(r"```json|```", "", response).strip()

    try:
        data = json.loads(cleaned)
        judgments = data.get("judgments", [])
    except Exception as e:
        print(f"[AI Suggestions] LLM judgment parse failed: {e}")
        print(response)
        return [], []

    relevant = []
    irrelevant = []

    for j in judgments:
        idx = j.get("id", -1) - 1
        if 0 <= idx < len(candidates):
            req_text = candidates[idx]["req"]
            if j.get("verdict", "").upper() == "RELEVANT":
                relevant.append(req_text)
                print(f"  [AI-SUGGESTED ✅ RELEVANT] {req_text[:80]}...")
                print(f"     Reason: {j.get('reason', '')}")
            else:
                irrelevant.append(req_text)
                print(f"  [AI-SUGGESTED ❌ IRRELEVANT] {req_text[:80]}...")
                print(f"     Reason: {j.get('reason', '')}")

    return relevant, irrelevant


def find_ai_suggested_requirements(extracted_requirements, srs_requirements, user_input):
    """
    Full pipeline:
    1. Detect candidate AI-suggested REQs via cosine similarity
    2. Score each candidate via LLM judgment
    3. Return only the confirmed relevant ones

    Returns:
        relevant_suggestions (list of str): REQ texts to bold+label in PDF
    """

    print("\n--- Detecting AI-Suggested Requirements ---")

    candidates = detect_ai_suggested_requirements(extracted_requirements, srs_requirements)

    if not candidates:
        print("  No AI-suggested requirements detected.")
        return []

    print(f"  Found {len(candidates)} candidate(s) not from user input. Scoring with LLM...")

    relevant, irrelevant = score_relevance_with_llm(candidates, user_input)

    print(f"  Result: {len(relevant)} relevant, {len(irrelevant)} irrelevant AI suggestions.")

    return relevant